name: hello
trigger:
  - main
pool:
  name: Default
variables:
  - name: name
    value: diego
stages: 
- stage: stage1
  jobs:
  - job: job1
    steps:
      - bash: |
          echo "hello $(name)"
      - task: AzureCLI@2
        inputs:
          azureSubscription: 3b6327ad-9a1f-4d42-81f8-548756cdce21
          scriptType: bash
          inlineScript: |
            az account list

