name: hello
trigger:
  - main
pool:
  name: Default
variables:
  - name: name
    value: diego
stages: 
- stage: stage1
  jobs:
  - job: job1
    steps:
      - bash: |
          echo "hello $(name)"
      - task: AzureCLI@2
        inputs:
          azureSubscription: devtest
          scriptType: bash
          scriptLocation: 'inlineScript'
          inlineScript: |
            az account list
